# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-04 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0002_jugador'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schemas.Team', verbose_name=b'equipo'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='name',
            field=models.CharField(max_length=255, verbose_name=b'jugador'),
        ),
    ]
