# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-04 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0003_auto_20190104_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='goals',
            field=models.IntegerField(default=0, verbose_name=b'cantidad de goles'),
        ),
    ]
