# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-04 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0004_jugador_goals'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='country',
            field=models.IntegerField(default=1, verbose_name=b'nacionalidad'),
            preserve_default=False,
        ),
    ]
