# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-04 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0006_auto_20190104_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name=b'equipo'),
        ),
    ]
